# Generated by Django 5.2.7 on 2025-10-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("query_api", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["pending", "processing", "shipped", "delivered", "cancelled"],
                    )
                ),
                name="order_status_valid",
            ),
        ),
    ]
